apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-monkey
  labels:
    app: chaos-monkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-monkey
  template:
    metadata:
      labels:
        app: chaos-monkey
    spec:
      containers:
        - name: chaos-monkey
          image: yassermog/yasser-chaos
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
